### ISSUE TITLE
Be able to get playlist information from a video that is attached to a playlist

### ISSUE THREAD

**Issue by jufabeck2202** [CodeDotJS/youtube-playlist#1]
It would be helpful if this plugin would be also capable to fetch playlist information from a URL where  a video is already selected like:
`https://www.youtube.com/watch?v=bgU7FeiWKzc&list=PLWKjhJtqVAbnZtkAI3BqcYxKnfWn_C704&index=1`
instead of the normal: 
`https://www.youtube.com/playlist?list=PLWKjhJtqVAbnZtkAI3BqcYxKnfWn_C704`

**Comment by CodeDotJS** [comment]
Can you mention what kind of playlist information you'd like to fetch from the URL?

**Comment by jufabeck2202** [comment]
Of course!
I want to be able to fetch the same information from a URL of a playlist where a video is already playing like you currently get from a normal playlist URL.
Maybe if you provide a URL like this
`https://www.youtube.com/watch?v=bgU7FeiWKzc&list=PLWKjhJtqVAbnZtkAI3BqcYxKnfWn_C704&index=1`
you can extract the "list" part from the URL `list=PLWKjhJtqVAbnZtkAI3BqcYxKnfWn_C704` and append it to the normal URL without a video selected `https://www.youtube.com/playlist?` and then you would be able to use the functions you currently implemented.

**Comment by CodeDotJS** [comment]
Sorry, I forgot to fix this. Anyway, you can update the package and use it the way you want. The requested feature has been implemented. Apologies for the delay caused. 

Thanks for reporting the issue.

**Comment by jufabeck2202** [comment]
@CodeDotJS  Thank you!
