### ISSUE TITLE
Add playlist title

### ISSUE THREAD

**Issue by Spimy** [CodeDotJS/youtube-playlist#12]
At the moment, you cannot get the title of the playlist from the provided URL. Would be nice to be able to its title as well.

**Comment by lefuturiste** [comment]
May fixed in PR #9

**Comment by Spimy** [comment]
@lefuturiste I'm not entirely sure what to do with that PR rip

**Comment by CodeDotJS** [comment]
@Spimy I just released the new version of this API on npm. The requested feature is now available.

Thank you.
