### ISSUE TITLE
Some time the playlist isn't loading to data

### ISSUE THREAD

**Issue by creamgod45** [CodeDotJS/youtube-playlist#14]
```javascript
ytlist(urls, ['name', 'url']).then(res => {
	playlist['name'] = res.data.name;
	playlist['list'] = res.data.playlist;
	cache['url'] , cache['name'] = "";
	var s = setInterval(() => {
		if (typeof playlist['list'] !== 'undefined' && playlist['list'].length > 0){
			clearInterval(s);
			for([k,v] of Object.entries(playlist['list'])){
				var titles = Buffer.from(v.name).toString('base64');
				cache['url']+=v.url+",";
				cache['name']+=titles+",";
			}
			cache['reg1'] = LZString.compress(cache['url']);
			cache['reg2'] = LZString.compress(cache['name']);
		}		
	}, 100);
});
```
input: urls = https://www.youtube.com/playlist?list=PLRBp0Fe2GpgmsW46rJyudVFlY6IYjFBIK
output: {name: '', playlist: Array(0)}

**Comment by Vaerys42** [comment]
Got the same
Just try to get the url and sometimes the array is empty

**Comment by CodeDotJS** [comment]
cc @moshfeu 

please take a look.

**Comment by callumok2004** [comment]
Please fix this, I cannot find any other workaround!

**Comment by creamgod45** [comment]
It is recommended to use google api to call video data which is more stable. @CodeDotJS

**Comment by CodeDotJS** [comment]
YouTube has changed how the used to render the content so cheerio is unable to grab anything from the webpage. One of the options is to heavily parse data which is presented in the form of JS, so I'm trying to approach this issue without bringing much complexity.

This should get fixed soon. I don't want to use Google API.

**Comment by CodeDotJS** [comment]
This issue has been fixed with the help of @dwahrens. 

Switch to the latest version to use it without any problem.

**Comment by moshfeu** [comment]
Thank you all! The fix is working 👍
I was out this business for some time.
