### ISSUE TITLE
Sorry man Doesn't seem like it's working anymore

### ISSUE THREAD

**Issue by her0me** [CodeDotJS/youtube-playlist#15]
Hi, I tried running your example code on npm through RunKit and that wouldn't even work, it just returns an empty Array/list with no data in it.  I have got it to give me the names a few times, but it's a fluke and I didn't even have the name tag in the function.

**Comment by CodeDotJS** [comment]
Additional ~ https://github.com/CodeDotJS/youtube-playlist/issues/14

I'm really busy these days. I'm not able to maintain any of my projects here. Will try to fix this issue as soon as possible. Apologies for the inconvenience.

**Comment by her0me** [comment]
Oh, yeah I guess that is the same issue.  No problem, thanks for the response.  I guess I will shift my project in another direction for now because I can't find any other anonymous javascript dependencies that will give me the links in a YouTube playlist.

**Comment by adityakale3** [comment]
Hey, Actually was facing the same issue, for playlist with videos more than 3 would return empty data set.

**Comment by CodeDotJS** [comment]
I'm working on it.

**Comment by kyungjoongo2** [comment]
Google seems to have changed the form of the response.

**Comment by kyungjoongo** [comment]
Can you tell me which response has information about the video?

**Comment by CodeDotJS** [comment]
@kyungjoongo right now, none.  https://github.com/CodeDotJS/youtube-playlist/issues/14#issuecomment-654032398

**Comment by dwahrens** [comment]
A workaround is to append `&disable_polymer=1` to any playlist url to retreive the old version of YouTube that cherrio can use. Example: **https://www.youtube.com/playlist?list=PLWKjhJtqVAbnZtkAI3BqcYxKnfWn_C704&disable_polymer=1**

Not sure how long this workaround will be around but I'm using it for now.

**Comment by yfenes** [comment]
> append `&disable_polymer=1` to any playlist url 

Worked for me! Thanks @dwahrens !  I feel really lucky that you just commented 18 minutes ago :D

**Comment by CodeDotJS** [comment]
@dwahrens thank you so much.

 https://github.com/CodeDotJS/youtube-playlist/commit/459eb95c05d438ffc42c4716c07a7b4bb94c9cc2 adds `&disable_polymer=1` the URL, so you don't have to add it manually.

As for now, this issue is fixed. Please update the package.

Once again, thank you.
