### ISSUE TITLE
Weekly downloads not found

### ISSUE THREAD

**Issue by IrfDev** [CodeDotJS/youtube-playlist#18]
I really want to know how many weekly downloads have these package on npm but it returns me 404.

<img width="381" alt="Captura de Pantalla 2020-09-18 a la(s) 0 19 31" src="https://user-images.githubusercontent.com/53235311/93559147-a9cb8080-f944-11ea-8351-38eb209c14b0.png">

**Comment by CodeDotJS** [comment]
Actually, that __`404`__ is __*not*__ an __error__. 

It's the actual number of times that the package has been downloaded over the period between __*2020-09-11*__  and  __*2020-09-17*__

**Comment by IrfDev** [comment]
Hahaha I know! I was joking :/
