### ISSUE TITLE
Does it require an API key?

### ISSUE THREAD

**Issue by elieobeid7** [CodeDotJS/youtube-playlist#5]
I don't see anywhere that this library requires a Youtube API key or a client ID, so I want to ask if it require one of those and where to use them?

If it doesn't require them, then is there a limit for the usage or limit for number of users?

**Comment by elieobeid7** [comment]
Why do I have issue ID #5 not 4# ? !

**Comment by CodeDotJS** [comment]
Check ~ https://github.com/CodeDotJS/youtube-playlist/issues/6
